### PR TITLE
Refactoring the Class and the test

### PR DESCRIPTION
**Pull request by JMasr**
Code review, now it is more pythonic!

### CODE REVIEW

**Comment by JMasr** [comment]
Hi @Eagleshot , thanks for the code. I just try to change some name and add decorator.
Do you know if it is possible make a video using the digiCamControler?

**Comment by Eagleshot** [comment]
Hey @JMasr, thank you really much for your contribution (and sorry for the late response)! I was able to record video on my camera using the following code:

``` Python
camera.show_live_view()
camera.run_cmd("do StartRecord")
time.sleep(5)
camera.run_cmd("do StopRecord")
```
I don't know if the live view is needed on every camera or just on mine (Nikon) and it didnt transfer the video to my pc but it should work as a workaraund. Hope this helps!

**Comment by Eagleshot** [comment]
Also as an FYI not all cameras supported by digiCamControl seem to also support video recordings via software so I would check compatibility first if it doesnt work with my code (https://digicamcontrol.com/cameras).

**Comment by JMasr** [comment]
Thanks a lot for your reply! Your tip works fine to record videos, and in my Nikon camera the live view was mandatory as well.

**Pull request merged**
